name: trainer
channels:
  - pytorch
  - conda-forge
dependencies:
  - fastprogress=1.0.3
  - h5py=3.7.0
  - hydra-core=1.2.0
  - omegaconf=2.2.3
  - pandas=1.5.2
  - pip=22.3.1
  - pre-commit=2.20.0
  - python=3.9
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - pip:
    - -e .
