arch:
  lstm:
    hidden_size: 64
    num_layers: 1
    dropout: 0.0
    bidirectional: False

checkpoint_dir: ${repo_dir}/checkpoints

cuda:
  num_gpus: -1

experiment: motion_ddp

num_workers: 0

repo_dir: ${oc.env:HOME}/pytorch-trainer

seed: 0

test:
  batch_size: 1
  data:
    x_dir: ${train.data.x_dir}
    y_dir: ${train.data.y_dir}

train:
  batch_size: 8
  epochs: 3
  data:
    x_dir: ${repo_dir}/src/MLtools/AudioLoader/tests/data/motion_wav
    y_dir: ${repo_dir}/src/MLtools/AudioLoader/tests/data/motion_rts
  lr: 0.001
